enabled:
  onJoinMenu: true

updates:
  menu-shown: false

options:
  gender: true
  name: true
  age: true

placeholders:
  female: "&d♀"
  male: "&b♂"
  non-binary: "&7X"

post-process:
  gender-commands:
    non-binary:
      executor: CONSOLE
      command: "/heal {PLAYER}"
    male:
      executor: CONSOLE
      command: "/heal {PLAYER}"
    female:
      executor: CONSOLE
      command: "/heal {PLAYER}"

  commands:
    heal-command:
      executor: CONSOLE
      command: "/heal {PLAYER}"

inventories:
  onJoin:
    menu-delay: 10000
  name:
    title: "Name"
    onlyName: false
    type: ANVIL #you can choose between Chest and Anvil :D
    anvil-gui:
      title: "Name"
      item:
        material: NAME_TAG
        custom-model-data: 10030
        displayName: "&aInsert your name"
        lore:
          - "&7Insert your name"
    action-element:
      onClick:
        type-name-in-chat: "&bType in the Chat your name and surname detached!"
        surname-needed: "&bYou must also enter the surname detached from the first name!"
        titleBar:
          enabled: true
          title: "&b&lDigit in chat"
          subtitle: "&7Your name."
  age:
    title: "Age"
    type: FURNACE #you can choose between Chest and Furnace :D
    options:
      min-age: 10
      max-age: 80
      #Max needs to be more than min and viceversa.
      #Min needs to be more than 0
    data:
      years:
        25:
          custom-model-data: 10038
          material: PAPER
          name: "&aClick to confirm (%actualage%)"
          lore:
            - "&7This is your age, click to confirm."

  gender:
    title: "Gender"


